var searchData=
[
  ['xcoroutinecreate_1152',['xCoRoutineCreate',['../group__xCoRoutineCreate.html',1,'']]],
  ['xsemaphorecreatebinary_1153',['xSemaphoreCreateBinary',['../group__xSemaphoreCreateBinary.html',1,'']]],
  ['xsemaphorecreatebinarystatic_1154',['xSemaphoreCreateBinaryStatic',['../group__xSemaphoreCreateBinaryStatic.html',1,'']]],
  ['xsemaphorecreatecounting_1155',['xSemaphoreCreateCounting',['../group__xSemaphoreCreateCounting.html',1,'']]],
  ['xsemaphorecreatecountingstatic_1156',['xSemaphoreCreateCountingStatic',['../group__xSemaphoreCreateCountingStatic.html',1,'']]],
  ['xsemaphorecreatemutex_1157',['xSemaphoreCreateMutex',['../group__xSemaphoreCreateMutex.html',1,'']]],
  ['xsemaphorecreatemutexstatic_1158',['xSemaphoreCreateMutexStatic',['../group__xSemaphoreCreateMutexStatic.html',1,'']]],
  ['xsemaphorecreaterecursivemutex_1159',['xSemaphoreCreateRecursiveMutex',['../group__xSemaphoreCreateRecursiveMutex.html',1,'']]],
  ['xsemaphorecreaterecursivemutexstatic_1160',['xSemaphoreCreateRecursiveMutexStatic',['../group__xSemaphoreCreateRecursiveMutexStatic.html',1,'']]],
  ['xsemaphoregive_1161',['xSemaphoreGive',['../group__xSemaphoreGive.html',1,'']]],
  ['xsemaphoregivefromisr_1162',['xSemaphoreGiveFromISR',['../group__xSemaphoreGiveFromISR.html',1,'']]],
  ['xsemaphoregiverecursive_1163',['xSemaphoreGiveRecursive',['../group__xSemaphoreGiveRecursive.html',1,'']]],
  ['xsemaphoretake_1164',['xSemaphoreTake',['../group__xSemaphoreTake.html',1,'']]],
  ['xsemaphoretakerecursive_1165',['xSemaphoreTakeRecursive',['../group__xSemaphoreTakeRecursive.html',1,'']]],
  ['xtasknotify_1166',['xTaskNotify',['../group__xTaskNotify.html',1,'']]],
  ['xtasknotifygive_1167',['xTaskNotifyGive',['../group__xTaskNotifyGive.html',1,'']]],
  ['xtasknotifystateclear_1168',['xTaskNotifyStateClear',['../group__xTaskNotifyStateClear.html',1,'']]],
  ['xtasknotifywait_1169',['xTaskNotifyWait',['../group__xTaskNotifyWait.html',1,'']]]
];
