var searchData=
[
  ['vcoroutineschedule_907',['vCoRoutineSchedule',['../group__vCoRoutineSchedule.html',1,'']]],
  ['vqueuedelete_908',['vQueueDelete',['../group__vQueueDelete.html',1,'']]],
  ['vsemaphorecreatebinary_909',['vSemaphoreCreateBinary',['../group__vSemaphoreCreateBinary.html',1,'']]],
  ['vsemaphoredelete_910',['vSemaphoreDelete',['../group__vSemaphoreDelete.html',1,'']]],
  ['vtaskdelay_911',['vTaskDelay',['../group__vTaskDelay.html',1,'']]],
  ['vtaskdelayuntil_912',['vTaskDelayUntil',['../group__vTaskDelayUntil.html',1,'']]],
  ['vtaskdelete_913',['vTaskDelete',['../group__vTaskDelete.html',1,'']]],
  ['vtaskendscheduler_914',['vTaskEndScheduler',['../group__vTaskEndScheduler.html',1,'']]],
  ['vtaskgetinfo_915',['vTaskGetInfo',['../group__vTaskGetInfo.html',1,'']]],
  ['vtaskgetruntimestats_916',['vTaskGetRunTimeStats',['../group__vTaskGetRunTimeStats.html',1,'']]],
  ['vtasklist_917',['vTaskList',['../group__vTaskList.html',1,'']]],
  ['vtaskpriorityset_918',['vTaskPrioritySet',['../group__vTaskPrioritySet.html',1,'']]],
  ['vtaskresume_919',['vTaskResume',['../group__vTaskResume.html',1,'']]],
  ['vtaskresumefromisr_920',['vTaskResumeFromISR',['../group__vTaskResumeFromISR.html',1,'']]],
  ['vtaskstartscheduler_921',['vTaskStartScheduler',['../group__vTaskStartScheduler.html',1,'']]],
  ['vtasksuspend_922',['vTaskSuspend',['../group__vTaskSuspend.html',1,'']]],
  ['vtasksuspendall_923',['vTaskSuspendAll',['../group__vTaskSuspendAll.html',1,'']]],
  ['vtimersettimerid_924',['vTimerSetTimerID',['../group__vTimerSetTimerID.html',1,'']]]
];
