var searchData=
[
  ['vcoroutineschedule_684',['vCoRoutineSchedule',['../group__vCoRoutineSchedule.html',1,'']]],
  ['vqueuedelete_685',['vQueueDelete',['../group__vQueueDelete.html',1,'']]],
  ['vsemaphorecreatebinary_686',['vSemaphoreCreateBinary',['../group__vSemaphoreCreateBinary.html',1,'']]],
  ['vsemaphoredelete_687',['vSemaphoreDelete',['../group__vSemaphoreDelete.html',1,'']]],
  ['vtaskdelay_688',['vTaskDelay',['../group__vTaskDelay.html',1,'']]],
  ['vtaskdelayuntil_689',['vTaskDelayUntil',['../group__vTaskDelayUntil.html',1,'']]],
  ['vtaskdelete_690',['vTaskDelete',['../group__vTaskDelete.html',1,'']]],
  ['vtaskendscheduler_691',['vTaskEndScheduler',['../group__vTaskEndScheduler.html',1,'']]],
  ['vtaskgetinfo_692',['vTaskGetInfo',['../group__vTaskGetInfo.html',1,'']]],
  ['vtaskgetruntimestats_693',['vTaskGetRunTimeStats',['../group__vTaskGetRunTimeStats.html',1,'']]],
  ['vtasklist_694',['vTaskList',['../group__vTaskList.html',1,'']]],
  ['vtaskpriorityset_695',['vTaskPrioritySet',['../group__vTaskPrioritySet.html',1,'']]],
  ['vtaskresume_696',['vTaskResume',['../group__vTaskResume.html',1,'']]],
  ['vtaskresumefromisr_697',['vTaskResumeFromISR',['../group__vTaskResumeFromISR.html',1,'']]],
  ['vtaskstartscheduler_698',['vTaskStartScheduler',['../group__vTaskStartScheduler.html',1,'']]],
  ['vtasksuspend_699',['vTaskSuspend',['../group__vTaskSuspend.html',1,'']]],
  ['vtasksuspendall_700',['vTaskSuspendAll',['../group__vTaskSuspendAll.html',1,'']]],
  ['vtimersettimerid_701',['vTimerSetTimerID',['../group__vTimerSetTimerID.html',1,'']]]
];
