var searchData=
[
  ['vcoroutineschedule_683',['vCoRoutineSchedule',['../group__vCoRoutineSchedule.html',1,'']]],
  ['vqueuedelete_684',['vQueueDelete',['../group__vQueueDelete.html',1,'']]],
  ['vsemaphorecreatebinary_685',['vSemaphoreCreateBinary',['../group__vSemaphoreCreateBinary.html',1,'']]],
  ['vsemaphoredelete_686',['vSemaphoreDelete',['../group__vSemaphoreDelete.html',1,'']]],
  ['vtaskdelay_687',['vTaskDelay',['../group__vTaskDelay.html',1,'']]],
  ['vtaskdelayuntil_688',['vTaskDelayUntil',['../group__vTaskDelayUntil.html',1,'']]],
  ['vtaskdelete_689',['vTaskDelete',['../group__vTaskDelete.html',1,'']]],
  ['vtaskendscheduler_690',['vTaskEndScheduler',['../group__vTaskEndScheduler.html',1,'']]],
  ['vtaskgetinfo_691',['vTaskGetInfo',['../group__vTaskGetInfo.html',1,'']]],
  ['vtaskgetruntimestats_692',['vTaskGetRunTimeStats',['../group__vTaskGetRunTimeStats.html',1,'']]],
  ['vtasklist_693',['vTaskList',['../group__vTaskList.html',1,'']]],
  ['vtaskpriorityset_694',['vTaskPrioritySet',['../group__vTaskPrioritySet.html',1,'']]],
  ['vtaskresume_695',['vTaskResume',['../group__vTaskResume.html',1,'']]],
  ['vtaskresumefromisr_696',['vTaskResumeFromISR',['../group__vTaskResumeFromISR.html',1,'']]],
  ['vtaskstartscheduler_697',['vTaskStartScheduler',['../group__vTaskStartScheduler.html',1,'']]],
  ['vtasksuspend_698',['vTaskSuspend',['../group__vTaskSuspend.html',1,'']]],
  ['vtasksuspendall_699',['vTaskSuspendAll',['../group__vTaskSuspendAll.html',1,'']]],
  ['vtimersettimerid_700',['vTimerSetTimerID',['../group__vTimerSetTimerID.html',1,'']]]
];
